### ISSUE TITLE
ALERT HUB Feedback and Issues

### ISSUE THREAD

**Issue by nnjemie** [IFRCGo/alert-hub-web-app#72]
**Map View**

- [x] IFRCGo/alert-hub-backend#50
- [x] #105
-  [x] IFRCGo/alert-hub-web-app#92
- [x] In the user stories, it mentions the ability to select a particular admin1 on the map to view its alerts. Has this functionality been completely removed with the list view, or could it be added back?
- [x] Paola emphasized that descriptions and instructions are crucial and should be prioritized, but they do not appear in the map view. Is it possible to include them on the initial view of the alert?

_Prototype view:_
 ![image](https://github.com/IFRCGo/alert-hub-web-app/assets/32084919/662aee55-818b-4fa7-9ea1-bc85f3f83a3c)

_Current view:_
![image](https://github.com/IFRCGo/alert-hub-web-app/assets/32084919/8c3dddcc-4834-4859-aa1d-c55306e6afc4)
 
- [x] IFRCGo/alert-hub-web-app#93

**Table View**

- [x] IFRCGo/alert-hub-web-app#96
- [x] When I click on "View Details" for an alert in the table, could it open in a new page or provide a way to return to the same page (with filtering intact) instead of redirecting me back to the map view?
- [x] IFRCGo/alert-hub-web-app#94
- [x] IFRCGo/alert-hub-web-app#90
- [x] The prototype's table features a button to copy the link of the alert, which is missing in the new system. Could this be added back in the new frontend?

**Alert detail:**

- [x] The area menu seems to take up a lot of space unnecessarily. It should work like a toggle, similar to info1 vs. info2, allowing for multiple areas. In the original version, all details like area description, altitude, ceiling, and area shape were neatly grouped under 'AREA 1', and the same pattern followed for 'AREA 2', if present. I thought you were working on this last week but maybe I misunderstood so could you please fix it?
P.S. AREA is described as "The container for all component parts of the area sub-element of the info sub-element of the alert message" and in comparison INFO is describes as "The container for all component parts of the info sub-element of the alert message"

_Current system:_
 ![image](https://github.com/IFRCGo/alert-hub-web-app/assets/32084919/428349da-202a-4568-b12d-5d69c0f36656)

_Old system_
 ![image](https://github.com/IFRCGo/alert-hub-web-app/assets/32084919/038e05da-9057-493c-a24c-a712b47503e7)

**Source feeds**

- [x] IFRCGo/alert-hub-web-app#95
- [x] When clicking on a card, could it open in a new page?.
- [x] It appears there are some duplicates in the system, particularly instances where organizations and languages are identical. Could we remove these actual duplicates for a cleaner database? For instance, as illustrated below:

![image](https://github.com/IFRCGo/alert-hub-web-app/assets/32084919/73f9587a-da27-4e07-8a27-b93d04eb947b)

cc @barshathakuri

**Comment by ypyelab** [comment]
- [x] Another point we would need to fix is the encoding of the text: ![image](https://github.com/IFRCGo/alert-hub-web-app/assets/37597139/f2f6600d-464d-48a0-af48-ef1853f60d33)

- [x] And that  the category filter in the map seems not to be working properly, when I filter by it, I see the same number of alerts as the unfiltered view

![image](https://github.com/IFRCGo/alert-hub-web-app/assets/37597139/842b2948-dfb2-401f-8c8c-084a3c2bd3c1)

**Comment by barshathakuri** [comment]
@ypyelab
- Could you please explain what you mean by "Another point we would need to fix is the encoding of the text"? Do you mean that the characters are rendered incorrectly, or do we need to preview in markdown font?

- The event categories filter was for tabular views. So we have removed it from the map filter.

**Comment by ypyelab** [comment]
Hi @barshathakuri! 

Thanks for the clarification of the event categories filter. 

And yes, for the display of the characters, I meant that some are being rendered incorrectly.

For example:
![image](https://github.com/IFRCGo/alert-hub-web-app/assets/37597139/d45589c7-ae45-49a9-829d-d98e03dc112c)

![image](https://github.com/IFRCGo/alert-hub-web-app/assets/37597139/793c7e6e-43b5-44b3-b651-b3dfdfd6c6b9)

**Comment by ypyelab** [comment]
Additionally, we would like to have an information icon at the side of the "All Ongoing Alerts" title, that when hovered display the following tooltip:

"The IFRC AlertHub shows warnings from authoritative agencies in countries. These warnings have a start time (when the event might happen) and an end time (when it's expected to be over). You'll only see warnings that are happening right now (their start time has already passed) but aren't finished yet (their end time hasn't come yet)."

The exact wording might vary in the next weeks, but this could work as a placeholder.

**Comment by barshathakuri** [comment]
@ypyelab, It will be quite challenging to monitor all the bugs and features within a single issue. Could we possibly create separate issues specifically for bugs, to streamline future maintenance and fixes? We have added an issue template for this purpose, it will greatly enhance our workflow. You can access the template through the following [link](https://github.com/IFRCGo/alert-hub-web-app/blob/feature/read-me/.github/ISSUE_TEMPLATE/bug-report---production.md).
cc: @nnjemie
